#!/bin/bash

  for dir in "$@"
  do
    rm "${dir}/TestsOutput/${dir}_report.txt"
    for loop in 1 2 3
    do  
      cd $dir
  
      # build
      make clean
      make enum_test
  
      # run
      echo "----------------------- $dir trial $loop -----------------------"
      ./enum_test
  
      cd ..
  done
done